export const prefix = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  DOCUMENT_SEND: 'DOCUMENT_SEND',
  DOCUMENT_SHARE: 'DOCUMENT_SHARE',
};

export const USER_LOGOUT = 'USER_LOGOUT';
export const GET_USER_DATA = 'GET_USER_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';

export const GET_PERMISSIONS = 'GET_PERMISSIONS';
export const SET_PERMISSIONS = 'SET_PERMISSIONS';

export const GET_SHARES = 'GET_SHARES';
export const SET_SHARES = 'SET_SHARES';

export const SET_MY_DOCUMENTS = 'SET_MY_DOCUMENTS';

export const SET_CRYPTED_PASSWORD = 'SET_CRYPTED_PASSWORD';

export const GET_TIMER = 'GET_TIMER';
export const SET_TIMER = 'SET_TIMER';

export const UPDATE_SHARES = 'UPDATE_SHARES';
